services:
  api-gateway:
    build: .
    container_name: api_gateway_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - shop_network
    restart: unless-stopped

networks:
  shop_network:
    external: true
